language: node_js
node_js:
  - '11'
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add gulp-cli
  - openssl aes-256-cbc -K $encrypted_714054dadbd0_key -iv $encrypted_714054dadbd0_iv
    -in tutor.json.enc -out ./tutor.json -d
  - openssl aes-256-cbc -K $encrypted_714054dadbd0_key -iv $encrypted_714054dadbd0_iv
    -in firebase-auth.js.enc -out ./src/js/modules/firestore/firebase-auth.js -d

install:
  - yarn install

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn deployToProduction
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: yarn deployToTest
    on:
      branch: test
