import {resultModal} from "../util/show-modal";

let dataCourses = {
  1: {
    "start": "2023-08-21T08:00:00.000Z",
    "startDate": "08月21日 16:00",
    "endDate": "08月21日 18:00",
    "subject": "翰林e家教 - 國中總複習數學",
    "unit": "國中總複習數學 - 第 6 堂 家教課堂",
    "icon": "./img/icon/ma.png",
    "tool": "國中總複習數學 - 第 6 堂 家教課堂",
    "eTutorUrl": "test",
    "points": 0,
    "hasCourseItem": false,
    "hasETutorCourseItem": true,
    "classBtnCss": "class-btn-done",
    "classBtnImg": "./img/btn-done-purple.png",
    "eTutorStatus": "done",
    "eTutorClassBtnCss": "class-btn-done",
    "eTutorClassBtnImg": "./img/btn-done-purple.png",
    "action": () => {},
    "eTutorAction": () => {
      resultModal(5, {
        "homework": "on-time",
        "tutorTime": "time-a",
        "concentrate": "concentrate-a",
        "interactive": "interactive-a"
      });
    }
  },
  2: {
    "start": "2023-08-21T08:00:00.000Z",
    "startDate": "08月21日 16:00",
    "endDate": "08月21日 18:00",
    "subject": "翰林e家教 - 國中總複習數學",
    "unit": "國中總複習數學 - 第 6 堂 家教課堂",
    "icon": "./img/icon/en.png",
    "tool": "國中總複習數學 - 第 6 堂 家教課堂",
    "eTutorUrl": "test",
    "points": 0,
    "hasCourseItem": false,
    "hasETutorCourseItem": true,
    "classBtnCss": "class-btn-add",
    "classBtnImg": "./img/btn-add.png",
    "eTutorStatus": "not-ready",
    "eTutorClassBtnCss": "disabled",
    "eTutorClassBtnImg": "./img/btn-eTutor-noclass.png",
    "action": () => {},
    "eTutorAction": () => {}
  },
  3: {
    "start": "2023-08-21T08:00:00.000Z",
    "startDate": "08月21日 16:00",
    "endDate": "08月21日 18:00",
    "subject": "翰林e家教 - 國中總複習數學",
    "unit": "國中總複習數學 - 第 6 堂 家教課堂",
    "icon": "./img/icon/na.png",
    "tool": "國中總複習數學 - 第 6 堂 家教課堂",
    "eTutorUrl": "test",
    "points": 0,
    "hasCourseItem": false,
    "hasETutorCourseItem": true,
    "classBtnCss": "class-btn-add",
    "classBtnImg": "./img/btn-add.png",
    "eTutorStatus": "ready",
    "eTutorClassBtnCss": "class-btn-start focus-animation",
    "eTutorClassBtnImg": "./img/btn-eTutor-ready.png",
    "action": () => {},
    "eTutorAction": () => {}
  },
  4: {
    "start": "2023-08-21T08:00:00.000Z",
    "startDate": "08月21日 16:00",
    "endDate": "08月21日 18:00",
    "subject": "翰林e家教 - 國中總複習數學",
    "unit": "國中總複習數學 - 第 6 堂 家教課堂",
    "icon": "./img/icon/pc.png",
    "tool": "國中總複習數學 - 第 6 堂 家教課堂",
    "eTutorUrl": "test",
    "points": 0,
    "hasCourseItem": false,
    "hasETutorCourseItem": true,
    "classBtnCss": "class-btn-add",
    "classBtnImg": "./img/btn-add.png",
    "eTutorStatus": "expired",
    "eTutorClassBtnCss": "",
    "eTutorClassBtnImg": "./img/btn-check-error.png",
    "action": () => {},
    "eTutorAction": () => {}
  },
  5: {
    "start": "2023-08-21T08:00:00.000Z",
    "startDate": "08月21日 16:00",
    "endDate": "08月21日 18:00",
    "subject": "翰林e家教 - 國中總複習數學",
    "unit": "國中總複習數學 - 第 6 堂 家教課堂",
    "icon": "./img/icon/ma.png",
    "tool": "國中總複習數學 - 第 6 堂 家教課堂",
    "eTutorUrl": "test",
    "points": 0,
    "hasCourseItem": false,
    "hasETutorCourseItem": true,
    "classBtnCss": "class-btn-add",
    "classBtnImg": "./img/btn-add.png",
    "eTutorStatus": "start",
    "eTutorClassBtnCss": "",
    "eTutorClassBtnImg": "./img/btn-eTutor-ready.png",
    "action": () => {},
    "eTutorAction": () => {}
  },
  6: {
    "start": "2023-08-21T08:00:00.000Z",
    "startDate": "08月21日 16:00",
    "endDate": "08月21日 18:00",
    "subject": "翰林e家教 - 國中總複習數學",
    "unit": "國中總複習數學 - 第 6 堂 自學課堂",
    "icon": "./img/icon/ma.png",
    "tool": "國中總複習數學 - 第 6 堂 自學課堂",
    "eTutorUrl": "",
    "points": 0,
    "hasCourseItem": true,
    "hasETutorCourseItem": false,
    "classBtnCss": "class-btn-start",
    "classBtnImg": "./img/btn-start.png",
    "eTutorStatus": "no-class",
    "eTutorClassBtnCss": "",
    "eTutorClassBtnImg": "",
    "action": () => {},
    "eTutorAction": () => {}
  },
  7: {
    "start": "2023-08-21T08:00:00.000Z",
    "startDate": "08月21日 16:00",
    "endDate": "08月21日 18:00",
    "subject": "翰林e家教 - 國中總複習數學",
    "unit": "國中總複習數學 - 第 6 堂 自學課堂",
    "icon": "./img/icon/ma.png",
    "tool": "國中總複習數學 - 第 6 堂 自學課堂",
    "eTutorUrl": "",
    "points": 0,
    "hasCourseItem": true,
    "hasETutorCourseItem": false,
    "classBtnCss": "class-btn-add",
    "classBtnImg": "./img/btn-add.png",
    "eTutorStatus": "no-class",
    "eTutorClassBtnCss": "",
    "eTutorClassBtnImg": "",
    "action": () => {},
    "eTutorAction": () => {}
  },
  8: {
    "start": "2023-08-21T08:00:00.000Z",
    "startDate": "08月21日 16:00",
    "endDate": "08月21日 18:00",
    "subject": "翰林e家教 - 國中總複習數學",
    "unit": "國中總複習數學 - 第 6 堂 自學課堂",
    "icon": "./img/icon/ma.png",
    "tool": "國中總複習數學 - 第 6 堂 自學課堂",
    "eTutorUrl": "",
    "points": 0,
    "hasCourseItem": true,
    "hasETutorCourseItem": false,
    "classBtnCss": "class-btn-check",
    "classBtnImg": "./img/btn-check.png",
    "eTutorStatus": "no-class",
    "eTutorClassBtnCss": "",
    "eTutorClassBtnImg": "",
    "action": () => {},
    "eTutorAction": () => {}
  },
  9: {
    "start": "2023-08-21T08:00:00.000Z",
    "startDate": "08月21日 16:00",
    "endDate": "08月21日 18:00",
    "subject": "翰林e家教 - 國中總複習數學",
    "unit": "國中總複習數學 - 第 6 堂 自學課堂",
    "icon": "./img/icon/ma.png",
    "tool": "國中總複習數學 - 第 6 堂 自學課堂",
    "eTutorUrl": "",
    "points": 0,
    "hasCourseItem": true,
    "hasETutorCourseItem": false,
    "classBtnCss": "class-btn-done",
    "classBtnImg": "./img/btn-done-purple.png",
    "eTutorStatus": "no-class",
    "eTutorClassBtnCss": "",
    "eTutorClassBtnImg": "",
    "action": () => {},
    "eTutorAction": () => {}
  },
  10: {
    "start": "2023-08-21T08:00:00.000Z",
    "startDate": "08月21日 16:00",
    "endDate": "08月21日 18:00",
    "subject": "翰林e家教 - 國中總複習數學",
    "unit": "國中總複習數學 - 第 6 堂 自學課堂",
    "icon": "./img/icon/ma.png",
    "tool": "國中總複習數學 - 第 6 堂 自學課堂",
    "eTutorUrl": "",
    "points": 0,
    "hasCourseItem": true,
    "hasETutorCourseItem": false,
    "classBtnCss": "class-btn-done",
    "classBtnImg": "./img/btn-done-purple.png",
    "eTutorStatus": "no-class",
    "eTutorClassBtnCss": "",
    "eTutorClassBtnImg": "",
    "action": () => {},
    "eTutorAction": () => {}
  },
  11: {
    "start": "2023-08-21T08:00:00.000Z",
    "startDate": "08月21日 16:00",
    "endDate": "08月21日 18:00",
    "subject": "翰林e家教 - 國中總複習數學",
    "unit": "國中總複習數學 - 第 6 堂 自學課堂",
    "icon": "./img/icon/ma.png",
    "tool": "國中總複習數學 - 第 6 堂 自學課堂",
    "eTutorUrl": "",
    "points": 0,
    "hasCourseItem": true,
    "hasETutorCourseItem": false,
    classBtnCss: 'class-btn-noclass',
    classBtnImg: './img/btn-noclass.png',
    "eTutorStatus": "no-class",
    "eTutorClassBtnCss": "",
    "eTutorClassBtnImg": "",
    "action": () => {},
    "eTutorAction": () => {}
  }
}

export default dataCourses
